### ISSUE TITLE
[BUG]: Microsoft Edge uninstall script leaves a blank app in start menu

### ISSUE THREAD

**Issue by Daksh777** [undergroundwires/privacy.sexy#73] opened 2021-04-18 05:32 UTC
### Describe the bug

![image](https://user-images.githubusercontent.com/43648146/115135302-3f430600-a035-11eb-8db8-a2deda75c379.png)
Restarting the system does not help

### OS

Windows 10 20H2 Build 19042.928

**Comment by undergroundwires** [comment] 2021-04-18 10:26
Hi, thanks for the report! Is it caused by removing legacy edge (system app) or chromium edge?

**Comment by Daksh777** [comment] 2021-04-18 13:00
> Hi, thanks for the report! Is it caused by removing legacy edge (system app) or chromium edge?

It's the Chromium Edge

**Comment by undergroundwires** [comment] 2021-04-25 17:06
I could not reproduced it following:

1. Install chromium edge using ([download url](https://go.microsoft.com/fwlink/?linkid=2108834&Channel=Stable&language=en))
2. Check where the shortcuts are created. The installer created one at `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Microsoft Edge.lnk`
3. Uninstall it using privacy.sexy
4. The shortcut does not exist anymore (uninstaller removes it)

We call the official uninstaller for chromium Edge but deleting Edge (legacy system app) does not use any uninstaller so it may leave some residual files. I'll check the shortcut situation for legacy edge.

**Comment by Daksh777** [comment] 2021-04-26 05:02
I did the exact same steps as you did and it unfortunately did not remove the shortcut for me.

Installed Edge Chromium:
![image](https://user-images.githubusercontent.com/43648146/116030976-696e7680-a67a-11eb-83b6-f1ec7306bf8d.png)

Used privacy.sexy script:
![image](https://user-images.githubusercontent.com/43648146/116031005-7723fc00-a67a-11eb-8b21-1ab7f97d7c2e.png)

No Microsoft Edge.ink in C:\ProgramData\Microsoft\Windows\Start Menu\Programs:
![image](https://user-images.githubusercontent.com/43648146/116031084-9cb10580-a67a-11eb-924a-064d08f80841.png)

**Comment by undergroundwires** [comment] 2021-04-26 15:33
Hi thanks for the sharing your findings again @Daksh777 , so I was wrong to guess that the icon in the start menu is that shortcut file. It seems to be something else. I am not sure which file/registry entry is being created for that blank app in that case.

**Comment by Daksh777** [comment] 2021-04-27 03:52
I am also unable to find the source of that blank entry in the start menu, let me know if you need me to do anything.

**Comment by undergroundwires** [comment] 2021-08-21 17:08
@Daksh777 could you look at where the shortcut is saved?

**Comment by Daksh777** [comment] 2021-08-23 06:47
I can't seem to find the location of the shortcut since there is no option to open the shortcut's location
![image](https://user-images.githubusercontent.com/43648146/130402605-d2bb6405-65c0-4dd3-b002-bd3edb7eac77.png)

After creating a shortcut link off of the icon to the desktop, all I see is this:
![image](https://user-images.githubusercontent.com/43648146/130402742-9b1b0dd8-703f-4471-8eb6-1fea43eb222a.png)

**Comment by undergroundwires** [comment] 2021-08-28 11:13
Thanks for responding back @Daksh777  . Maybe it's in `%UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs`?

**Comment by Daksh777** [comment] 2021-08-28 11:38
No, it's not present there either.
I searched through the whole system (using Search Everything) to find Microsoft Edge shortcuts, deleted them all but it still is present there.

**Comment by undergroundwires** [comment] 2021-08-28 14:56
Giving one last shot, is it in `%UserProfile%\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch` ?

**Comment by Daksh777** [comment] 2021-08-29 03:24
While there was a shortcut in that location, deleting it had no effect.

**Comment by oldcastlehq** [comment] 2021-09-22 07:29
I have exactly the same issue. I'm using Windows 10 Home 21H1

**Comment by eebssk1** [comment] 2021-10-01 10:40
it's just leftover/dummy package from the old win10 version which is same as the legacy edge. However i didn't see this entry after uninstalling new edge. According to some report on google force removing this dummy from system driver may probably break windows updates.

**Comment by bardiarajabi** [comment] 2022-02-14 09:11
@undergroundwires @Daksh777 this will do:
https://dl.malwarewatch.org/multipurpose/UninstallEdge.zip or attachment
un-zip it and run Uninstall Edge.cmd as **_ADMIN_**(Disable defender before running)
this will remove **_LEGACY_** version of edge
can be used after uninstalling edge **_CHROMIUM_**
[UninstallEdge.zip](https://github.com/undergroundwires/privacy.sexy/files/8059353/UninstallEdge.zip)

![image](https://user-images.githubusercontent.com/69072090/153833968-c2ad0395-f801-45cf-a6b4-c83d93087123.png)

**Comment by undergroundwires** [comment] 2022-03-06 22:01
This is golden. I have not tested this against residual files because I was never be able to produce this. But we should still add this functionality in privacy.sexy.

The script you included calls `install_wim_tweak.exe` with `Microsoft-Windows-Internet-Browser-Package`. Someone shared source code code for [`install_wim_tweak.exe`](https://github.com/shiitake/win6x_registry_tweak/blob/master/Program.cs). It removes [CBS package](https://techcommunity.microsoft.com/t5/ask-the-performance-team/understanding-component-based-servicing/ba-p/373012) registry values that we don't do here.

The logic written there has two issues:

- Depends on legacy Windows component(s).
- It's one way only, no back-ups or no revert logic.

When I find the time, I will rewrite this using PowerShell, modern components and a solid way to revert with backups. We can benefit from this CBS package cleanup on other places as well.

Thank you for the solution @bardiarajabi and all your contributions. You have been helping a lot to make this a better software.

**Comment by undergroundwires** [comment] 2022-03-06 22:02
This is golden. I have not tested this against residual files because I was never be able to produce this. But we should still add this functionality in privacy.sexy.

The script you included calls `install_wim_tweak.exe` with `Microsoft-Windows-Internet-Browser-Package`. Someone shared source code code for [`install_wim_tweak.exe`](https://github.com/shiitake/win6x_registry_tweak/blob/master/Program.cs). It removes [CBS package](https://techcommunity.microsoft.com/t5/ask-the-performance-team/understanding-component-based-servicing/ba-p/373012) registry values that we don't do here.

The logic written there has two issues:

- Depends on legacy Windows component(s).
- It's one way only, no back-ups or no revert logic.

When I find the time, I will rewrite this using PowerShell, modern components and a solid way to revert with backups (of registry settings). We can benefit from this CBS package cleanup on other places as well.

Thank you for the solution @bardiarajabi and all your contributions. You have been helping a lot to make this a better software.

**Comment by bardiarajabi** [comment] 2022-03-07 08:16
@undergroundwires Yes only legacy windows components.
btw I found it on a youtube channel called endermanch which is advanced in windows tips/tricks.
Channel: https://www.youtube.com/channel/UCWb-66XSFCV5vgKEbl22R6Q
Video: https://youtu.be/g1dMF-W0d04?t=183
P.S.: At the time that he uploaded the video it was the only legacy edge, not chromium.

**Comment by Tharki-God** [comment] 2022-03-19 03:19
doesnt work

**Comment by Tharki-God** [comment] 2022-03-23 22:46
shell:appsfolder is where the shortcut is. and UWP apps gets added here automatically from what i got to know and please find a working solution the problem. the blank shortcut gives me anxiety

**Comment by bardiarajabi** [comment] 2022-03-24 18:46
@Tharki-God Can a normal or admin user delete the shortcut?

**Comment by Tharki-God** [comment] 2022-03-24 19:07
> @Tharki-God Can a normal or admin user delete the shortcut?

no they cant, i am using the in-built admin account as my daily driver and i cant. upon searching you cant edit that location. uwp apps installed get shortcut there automatically and exe files with the help of traditional start menu folder. so there must be some way to remove edge from installed list.

**Comment by bardiarajabi** [comment] 2022-03-25 17:25
> > @Tharki-God Can a normal or admin user delete the shortcut?
> 
> no they cant.
So it can't be helped.

**Comment by bardiarajabi** [comment] 2022-03-28 11:58
@Tharki-God Your solution was good if the trusted installer has access to that folder.

**Comment by undergroundwires** [comment] 2023-10-02 16:54
I've been able to reproduce the issue consistently now, so I will work on this. There will be a few iterations until this will be fixed. Thank you to everyone for providing context.

**Delete all related `.lnk` files**

First improvement I'm planning to do is to remove all the shortcut files (`.lnk`) files. According to my tests they exist at (tested on 22H2):

| Path | Windows 11 | Windows 10 |
| ---- |:----------:|:----------:|
| `%ProgramData%\Microsoft\Windows\Start Menu\Programs\Microsoft Edge.lnk` | ✅ Exists | ✅ Exists |
| `%AppData%\Microsoft\Internet Explorer\Quick Launch\Microsoft Edge.lnk` | ✅ Exists | ✅ Exists |
| `%AppData%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Microsoft Edge.lnk` | ✅ Exists | ✅ Exists |
| `%Public%\Desktop\Microsoft Edge.lnk` | ✅ Exists | ✅ Exists |
| `%SystemRoot%\System32\config\systemprofile\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\Microsoft Edge.lnk` | ✅ Exists | ✅ Exists |
| `%UserProfile%\Desktop\Microsoft Edge.lnk` | ❌ Missing | ❌ Missing |

I have also tested and can verify that the default uninstaller(s) provided by the OS do not delete all of them.

**`DisableEdgeDesktopShortcutCreation`**

After some research I found the key `DisableEdgeDesktopShortcutCreation` that's supposed to disable creation of Edge shortcut for user profiles. This key is highly undocumented. According to my tests, Edge does not add shortcut to every user profile but only to public desktop (`%Public%\Desktop\Microsoft Edge.lnk`) and this file we can just remove, so I do not see the need to set this key to true.

**Ongoing Work**

While deleting these files is a positive step, it does not completely solve the issue as the icon remains in the start menu. I will continue to explore other methods and approaches to fully resolve this.

**Comment by undergroundwires** [comment] 2023-10-02 17:44
> shell:appsfolder

This is a "fake folder" and I have yet find a way to modify it.

> HKCU\Software\Microsoft\Edge, HKLM\SOFTWARE\Wow6432Node\Microsoft\Edge

These keys include settings for Edge but do not seem to have any effect on start menu icon. For me, deleting them was persistent across reboots. HKLM key was gone for good and HKCU key was recreated with an empty value but missing all other configurations. Maybe we should add deletion of them manually once Edge is uninstalled 🤔

> https://james-rankin.com/articles/how-to-remove-uwp-apps-on-windows-10-v1803/ if this helps

His suggestion of renaming files in `c:\programdata\microsoft\windows\apprepository\packages` makes sense. However there's no metadata (folder) there about Edge, so it does not work. But I will still update privacy.sexy to handle this directory for system app removal, so thank you for the contribution ❤️

**Comment by undergroundwires** [comment] 2023-11-04 12:35
Years after, this is finally fixed and released in [0.12.6](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.6) 🚀. The solution was to remove appx package. Please create a new issue in future if you detect something.

**Closed by undergroundwires** 2023-11-04 12:35 UTC
Labels: bug

**Comment by Daksh777** [comment] 2023-11-12 11:06
That is amazing, thanks a ton for working on this even after years @undergroundwires, haha!
I hope you have a great day :)
