### ISSUE TITLE
[Bug]: Error when applying the `Disable Windows feedback collection` tweak

### ISSUE THREAD

**Issue by guihkx** [undergroundwires/privacy.sexy#381] opened 2024-07-05 14:12 UTC
### Description

I got the following error on a clean install of Windows 11 Pro 24H2 (build 26100.1000), using privacy.sexy version 0.13.5:

```
--- Disable Windows feedback collection
The operation completed successfully.
out-file : FileStream was asked to open a device that was not a file. For support for devices like 'com1:' or 'lpt1:', call CreateFile, then use the FileStream
constructors that take an OS handle as an IntPtr.
At line:1 char:1
+ reg delete "HKCU\SOFTWARE\Microsoft\Siuf\Rules" /v "PeriodInNanoSecon ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (:) [Out-File], NotSupportedException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand

The operation completed successfully.
The operation completed successfully.
```

### How can the bug be recreated?

1. Apply the `Disable Windows feedback collection` tweak

### Operating system

Windows 11 Pro 24H2 (build 26100.1000)

**Comment by undergroundwires** [comment] 2024-07-06 12:08
I can reproduce this. 

Just like #380, it was introduced as part of 0.13.4 in [commit cec0b4b](https://github.com/undergroundwires/privacy.sexy/commit/cec0b4b4f63c3563a0e7923ce6324a38d71a3955#diff-cc6832e8ee0b6b22d33fa5081a4ca1a4ffebf24d56d590d2fc52886a5025e9bfR4750). It runs the command `reg delete "HKCU\SOFTWARE\Microsoft\Siuf\Rules" /v "PeriodInNanoSeconds" /f 2>nul` which is correct, but runs this incorrectly as PowerShell (using `RunPowerShell`) meanwhile it's a batch command (should have used `RunInlineCode` function).

I will go for the bigger solution for this too. Instead of running `reg delete..` commands I will create a shared function in [`windows.yaml`](https://raw.githubusercontent.com/undergroundwires/privacy.sexy/0.13.5/src/application/collections/windows.yaml) called `DeleteRegistryValue` or similar, and refactor all code that runs `reg delete ..` to that function. This will protect against typos in reg delete commands and this kind of mistakes in future.

This will take some time but will be fixed as part of next patch.

Thank you for the great bug reports @guihkx, making our software better, feel free to inform us if you encounter anything else or any suggestion to implement in new issues.

**Comment by undergroundwires** [comment] 2024-08-13 12:34
Since [0.13.6](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.6), all registry operations are standardized/streamlined fixing this bug and preventing future bugs. I also added reversibility to everything possible. It was marathon going through all registry operations and testing but its done now 🚀🎉🥳

**Closed by undergroundwires** 2024-08-13 12:34 UTC
Labels: bug
