### ISSUE TITLE
[BUG]: Microsoft Edge still alive after removal

### ISSUE THREAD

**Issue by d3cim** [undergroundwires/privacy.sexy#309] opened 2024-01-12 20:39 UTC
### Description

Microsoft Edge still trying to ping Microsoft after uninstalling it.

### OS

Microsoft Windows 10 IoT Enterprise
10.0.19045 Build 19045

### Reproduction steps

Install a generic traffic monitor like Wireshark or any good firewall like simplewall and see these pings coming from `microsoftedgeupdate.exe` happen time to time during a normal session.

The file is stored in `C:\Program Files (x86)\Microsoft\EdgeUpdate` folder.

### Scripts

A custom version between Strict and All.
 [privacy-script-hard.txt](https://github.com/undergroundwires/privacy.sexy/files/13923797/privacy-script-hard.txt)

### Additional information

I can also notice `msedgewebview2.exe` do some requests coming from `C:\Program Files (x86)\Microsoft\EdgeWebView\Application\120.0.2210.121` folder.

I don't know if it is something strictly related to MS Edge but blocking them doesn't seem to affect the system usability.

I would like to thank you for your work and your tool.. it is simply amazing..

**Comment by quindecim** [comment] 2024-01-12 21:00
Here a capture:

```
"‎12/‎01/‎2024 ‏‎21:41:24","DESKTOP\admin","C:\program files (x86)\microsoft\edgeupdate\microsoftedgeupdate.exe","20.7.47.135","443 (https)","tcp"
"‎12/‎01/‎2024 ‏‎21:41:24","DESKTOP\admin","C:\program files (x86)\microsoft\edgeupdate\microsoftedgeupdate.exe","13.107.42.16","443 (https)","tcp"
```

**Comment by undergroundwires** [comment] 2024-01-13 14:41
Could you test uninstalling the updates in an elevated `cmd.exe` like this and see if it works:

```batchfile
"C:\Program Files (x86)\Microsoft\EdgeUpdate\MicrosoftEdgeUpdate.exe" /uninstall
```

It would be also nice to test it that it can be reinstalled using:

```batchfile
"C:\Program Files (x86)\Microsoft\EdgeUpdate\MicrosoftEdgeUpdate.exe" /install
```

Other option would be to stop updates according to [Microsoft docs](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-update-policies):

```batchfile
reg add "HKLM\SOFTWARE\Policies\Microsoft\EdgeUpdate" /v "UpdateDefault" /t "REG_DWORD" /d "0" /f
```

Removal of web view would break any third party or Microsoft application that tries to render native Windows browser inside. `msedgewebview2.exe` is most likely being used by another application in your case, so that one would break if we get rid of web view.

**Comment by d3cim** [comment] 2024-01-16 18:33
> Could you test uninstalling the updates in an elevated `cmd.exe` like this and see if it works:
> 
> ```batchfile
> "C:\Program Files (x86)\Microsoft\EdgeUpdate\MicrosoftEdgeUpdate.exe" /uninstall
> ```
This results in nothing, the file still present in directory.
> 
> It would be also nice to test it that it can be reinstalled using:
> 
> ```batchfile
> "C:\Program Files (x86)\Microsoft\EdgeUpdate\MicrosoftEdgeUpdate.exe" /install
> ```
This results in an error message: 
> 
![sefg](https://github.com/undergroundwires/privacy.sexy/assets/49964366/b41eca4d-928a-47f8-ac54-0c41f8c30588)

> I then wonder if these services `edgeupdate` and `edgeupdatem` would be left after running the official uninstaller. You can check their existing with following PowerShell:
> 
> ```powershell
> (Get-Service -Name edgeupdate).StartType
> (Get-Service -Name edgeupdatem).StartType
> ```
This is the PS results: 
> 
![fdgdfh](https://github.com/undergroundwires/privacy.sexy/assets/49964366/e2d33eae-9488-4f9b-b200-8c89a1f9beb6)

> Other option would be to stop updates according to [Microsoft docs](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-update-policies), but this probably won't work is only designed for enterprises as usual:
> 
> ```batchfile
> reg add "HKLM\SOFTWARE\Policies\Microsoft\EdgeUpdate" /v "UpdateDefault" /t "REG_DWORD" /d "0" /f
> ```
I'm on an Enterprise version and I tried to add these reg value but I can notice the service running again.

**Comment by undergroundwires** [comment] 2024-06-18 16:41
Thanks for the guidance and update @ltguillaume.

It sounds sad to rely on downloading and using a  proprietary executable.

What do you think? Should privacy.sexy host this file, download/use it and remove?

**Comment by undergroundwires** [comment] 2024-06-21 10:47
Using latest setup.exe from ` C:\Program Files (x86)\Microsoft\Edge\Application\126.0.2592.68\` worked for me. What version are you using? Can you share logs from "Remove Edge through official installer"?

**Comment by undergroundwires** [comment] 2024-06-21 10:48
Using latest setup.exe from ` C:\Program Files (x86)\Microsoft\Edge\Application\126.0.2592.68\` worked for me. What version are you using? Can you share logs from "Remove Edge through official installer"?

I can reproduce that the updater is not removed and exist at `C:\Program Files (x86)\Microsoft\EdgeUpdate`.

**Comment by undergroundwires** [comment] 2024-06-21 11:02
Using latest `setup.exe` from ` C:\Program Files (x86)\Microsoft\Edge\Application\126.0.2592.68\` works fine on Windows 11 23H2.

However, it fails for Windows 10 22H2:

```
Uninstalling through uninstaller: C:\Program Files (x86)\Microsoft\Edge\Application\126.0.2592.68\Installer\setup.exe
Failed to uninstall, uninstaller failed with exit code 93.
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
```

So the problem is only affects Windows 10 using the latest `setup.exe`.

I can reproduce that the updater is not removed and exist at `C:\Program Files (x86)\Microsoft\EdgeUpdate`.

**Comment by undergroundwires** [comment] 2024-06-21 11:19
Using latest `setup.exe` from ` C:\Program Files (x86)\Microsoft\Edge\Application\126.0.2592.68\` works fine on Windows 11 23H2.

However, it fails for Windows 10 22H2:

```
Uninstalling through uninstaller: C:\Program Files (x86)\Microsoft\Edge\Application\126.0.2592.68\Installer\setup.exe
Failed to uninstall, uninstaller failed with exit code 93.
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
```

So the problem is only affects Windows 10 using the latest `setup.exe`.

Exit code 93 leads also errors for winget: https://github.com/microsoft/winget-cli/issues/1286. We should be watching this issue to see any official explanation.

@ltguillaume, these lines creates "fake existence" of legacy edge app:

```ps1
New-Item -Path "$env:SystemRoot\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe" -ItemType Directory -ErrorAction SilentlyContinue -Force 
New-Item -Path "$env:SystemRoot\SystemApps\Microsoft.MicrosoftEdge_8wekyb3d8bbwe" -ItemType File -Name 'MicrosoftEdge.exe' -Force 
```

And interestingly, it actually led to succesfull uninstallation of Edge on Windows 10 22H2 🥳. It means that `setup.exe` on Windows 10 checking the existence of legacy Edge and rejects uninstallation if it does note exist. I will fix that in a patch release, thank you for another great contribution @ltguillaume.

I can reproduce that the updater is not removed and exist at `C:\Program Files (x86)\Microsoft\EdgeUpdate`.

**Comment by undergroundwires** [comment] 2024-06-21 13:16
To close this issue, we need to take decisions about EdgeUpdate.

We could provide a script to delete it but then it will also affect WebView2.
WebView2 [relies on EdgeUpdate](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#detect-if-a-suitable-webview2-runtime-is-already-installed) for updates.

We could add a new category as `Remove Edge (Chromium) components` with two scripts to keep them separate for advanced users:
- `Remove WebView2`
- `Remove Edge updater (disables Edge and WebView2 updates)`

Does this make sense? If yes should they be under:

a. `Remove bloatware` category directly.
b. Add under `Remove Windows apps > Remove system apps > `. This category was designed for UWP apsp but these are for advanced users and make sense to isolated them outside the main category under more advanced one.
c. Another idea?

**Comment by undergroundwires** [comment] 2024-06-21 14:07
Most novice user would think way:

I want to remove Edge, let me click on "Remove Edge (Chromium)", and then they get updates and WebView2 uninstalled too.

Separating other stuff (updates + webview2) to **Edge components** would prevent them from making mistakes i.e. removing, blocking stuff that may be useful.

So a categorization to simplify risk management would be beneficial, but unsure what's the best way.

**Comment by undergroundwires** [comment] 2024-06-21 15:03
Thanks for feedback, let's leave that category for the apps. And I agree with renaming. I can merge a PR for it as I may forget this change.

I'll add stopping Edge updates + and the fix for Windows 10 and close the issue. We can create a new issue for disabling WebView2 later if we see necessary.

**Comment by undergroundwires** [comment] 2024-06-27 13:06
[0.13.5](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.5) is now released 🚀.

Both the removal fix and disabling of auto-updates are released.
Disabling auto-updates are under `Configure Programs > Configure Browsers > Configure Edge > Disable Edge and WebView2 automatic updates`.
Added also **Disable automatic installation of Edge and WebView** under this category which is recommended on Standard.

Meanwhile looking at this, added tens of other ways to configure Edge. It resolves lot of privacy issues.

Credit given in release notes to @ltguillaume and @d3cim. Thank you again.

If we want to delete/uninstall WebView2, we can create a new issue. Closing this.

**Comment by undergroundwires** [comment] 2024-06-27 13:06
[0.13.5](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.5) is now released 🚀.

Both the removal fix and disabling of auto-updates are released.
Disabling auto-updates are under `Configure Programs > Configure Browsers > Configure Edge > Disable Edge and WebView2 automatic updates`.
Added also **Disable automatic installation of Edge and WebView** under this category which is recommended on Standard.

Meanwhile looking at this, added tens of other ways to configure Edge. It resolves lot of privacy issues.

Credit given in release notes to @ltguillaume and @d3cim. Thank you again.

If we want to delete/uninstall WebView2, we can create a new issue. Closing this.

**Closed by undergroundwires** 2024-06-27 13:06 UTC
Labels: bug
