### ISSUE TITLE
[BUG]: Disabling Windows Defender Services requires NT Authority

### ISSUE THREAD

**Issue by ponei** [undergroundwires/privacy.sexy#74] opened 2021-04-22 13:09 UTC
### Describe the bug

Windows Defender service disabling scripts don't work under normal admin permissions; Changing some registry keys require NT Authority.

### OS
Edition	Windows 10 Home Single Language
Version	20H2
Compilação do SO	19042.928
Experiência	Windows Feature Experience Pack 120.2212.551.0

### Scripts

The whole "Disable Windows Defender Services" group

### Additional information

 I used a tool called PowerRun (https://www.sordum.org/9416/powerrun-v1-4-run-with-highest-privileges/) that emulates a process being called from TrustedInstaller, giving those extra permissions -- then the script ran without any errors. Also, consider adding more registry changes for better disabling (https://github.com/W4RH4WK/Debloat-Windows-10/issues/273#issuecomment-743973414).

**Comment by undergroundwires** [comment] 2021-08-21 17:07
Thank you for your report. I can reproduce this. I'll add the scripts you suggest in the next minor version.

Regarding a better solution, changing protected registry areas can be done using PowerShell which is even used by [Microsoft](https://github.com/microsoft/SDN/blob/master/Containers/InstallPrivateCloudPlugin.ps1). If I'd appreciate if some could PoC with it and share I'd appreciate. I'm prioritizing #53 which will make it easy to embed larger PowerShell code like this in privacy.sexy.

**Comment by undergroundwires** [comment] 2021-08-30 15:38
🎉 I wrote a working PoC with PowerShell. It will be added in privacy.sexy soon.

Is there any documentation on exactly which registry keys/tree are protected? Or I'd be happy for if you could share which registry keys that failed for you.

**Comment by undergroundwires** [comment] 2021-08-30 15:38
🎉 I wrote a working PoC with PowerShell. It will be added in privacy.sexy soon.

Is there any documentation on exactly which registry keys/tree are protected? Or I'd be happy for if you could share which registry keys that failed for you.

**Comment by ponei** [comment] 2021-08-31 01:12
Personally I had problems with ControlSet001, ControlSet002 and CurrentControlSet
I couldn't find documentation citing that it needs higher permission unfortunately. I tried changing them manually via regedit on my main machine and it worked without additional permission gains; maybe there's some layer of protection that you can disable that allows changing it without additional permissions?

**Comment by undergroundwires** [comment] 2021-09-01 06:28
Thank you. I tested it and yes you're right. I can reproduce this. They're under `Disable Windows Defender services`, and I get `ERROR: Access is denied` for them. So we should take ownership of each key before setting them. The reason it worked on your machine is probably because you took ownership of them before. And they're not owned solely by NT Authority anymore.

I also realized that some keys under `HKLM\SOFTWARE\Policies\Microsoft\Windows Defender` are protected. So we should also take ownership of keys there before modifying them.

**Comment by undergroundwires** [comment] 2021-09-08 16:33
I can modify the rights on `HKLM\SOFTWARE\Policies\Microsoft\Windows Defender` so local administrator group is granted access (along with NT Authority) and can change it. However I could not get it working for some services under `CurrentControlSet\Services` such as `reg add "HKLM\SYSTEM\CurrentControlSet\Services\WinDefend" /v "Start" /t REG_DWORD /d "4" /f`. Fix for the first part will be in the next version, so hopefully others can work on fixing the services part. Solutions like PowerRun are not very portable and we can't ship an UI application them along with privacy.sexy, but until the script is working for disabling service I'll put documentation for disabling Windows Defender services linking to this issue so people can use to run the scripts through it.

**Comment by ChrisDek** [comment] 2021-10-06 12:00
Even if all permissions are fine there is a relatively new feature called "tamper protection" that makes disabling defender from scripts (nealry) impossible. See https://techrechard.com/completely-disable-microsoft-defender-in-windows-11/ for a tutorial with pictures

**Comment by ponei** [comment] 2021-10-08 13:26
> Even if all permissions are fine there is a relatively new feature called "tamper protection" that makes disabling defender from scripts (nealry) impossible. See https://techrechard.com/completely-disable-microsoft-defender-in-windows-11/ for a tutorial with pictures

Windows 11 is fairly new and it changed quite a bit regarding system integrity. Give it some time and people will start messing with it; Then we'll see how it goes.

**Closed** 2021-10-29 18:21 UTC
Labels: bug
