### ISSUE TITLE
Script runtime errors (win10x64 2004)

### ISSUE THREAD

**Issue by necros2k7** [undergroundwires/privacy.sexy#51] opened 2021-01-04 05:49 UTC
--- XPS Viewer capability
В строке отсутствует завершающий символ: '.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString

**Comment by undergroundwires** [comment] 2021-01-05 21:27
Hi, thanks for the report. Both scripts will be improved in next version. I'll release the fixes/improvements in a week or two.

I spun up a VM with x64 windows 2004. I ran both `Windows Security GUI (Sec Health UI)` and `XPS Viewer capability` scripts.

**Capabilities**

I could reproduce the problem for capabilities. It's a bug in the newest version caused by a [second apostrophe typo](https://github.com/undergroundwires/privacy.sexy/blob/c4ec6a1445d2fd5eb923c97b54aee01e272e13a8/src/application/application.yaml#L4061-L4062). It will be fixed in the next version.

**Uninstalling system apps**

I could not reproduce the problem with `PermissionDenied` for uninstalling system apps. It worked fine on my VM. It takes ownership of the folder as an administrator to avoid `PermissionDenied`. Probably [commands before](https://github.com/undergroundwires/privacy.sexy/blob/3455a2ca6ce13f9b0e866d88532a5c3d6de30d4d/src/application/application.yaml#L4153-L4154) (`takeown` or `icacls`) has failed. But you could not see the error as they're not printed (swollen by `| Out-Null`). I'll ensure that errors are shown in the next version to debug this further.

I'd appreciate if you could open `cmd` and  test running

- `takeown /f  "C:\Windows\SystemApps\Microsoft.Windows.SecHealthUI_cw5n1h2txyewy" /r /d y`
- icacls "C:\Windows\SystemApps\Microsoft.Windows.SecHealthUI_cw5n1h2txyewy"/grant administrators:F /t

And tell me if one of them fail with error.

**Virtualbox error**

I'd be happy to solve this as well. Would you mind testing one thing to get more information:

1. Open CMD (terminal) as administrator.
2. Run the script using its full path to script e.g. by running `"C:/Users/{user}/downloads/privacy-script.bat"`.
3. You'll be able to see the error message and what's causing it to close like this. Please copy paste the error.

**Comment by necros2k7** [comment] 2021-01-06 00:14
takeown /f "C:\Windows\SystemApps\Microsoft.Windows.SecHealthUI_cw5n1h2txyewy" /r /d y    - OK
 icacls "C:\Windows\SystemApps\Microsoft.Windows.SecHealthUI_cw5n1h2txyewy"/grant administrators:F /t  -
failed with Unacceptable parameter  "administrators:F"

**Closed** 2021-01-06 14:24 UTC
Labels: bug
