### ISSUE TITLE
For modifying Firefox use user.js instead of modifying prefs.js

### ISSUE THREAD

**Issue by silverhook** [undergroundwires/privacy.sexy#232] opened 2023-08-09 18:20 UTC
### Problem description

When it comes to modifying Firefox settings, the script currently searches for different `prefs.js` and modifies it there.

This is heavily discouraged:

> **Preferences Saving**
> 
> Usually when the user specifically commits a preference change via user interface such as the Preferences dialog, the application saves the change by overwriting `prefs.js`. On application exit, all user-set preferences are saved to `prefs.js`. This also means that preferences initially set by `user.js` will also be saved to `prefs.js`.
> 
> > Do **NOT** edit `prefs.js` directly.
> 
> Note the application never changes `user.js`, so on launch `user.js` overrides conflicting preferences from the previous application session.
> 
> When `prefs.js` is written, it only saves user preferences which are different from the default. The exception to this is a preference read using `sticky_pref()` - these preference will be written whenever the preference has a user value even when it is the same as the default.
> 

https://udn.realityripple.com/docs/Mozilla/Preferences/A_brief_guide_to_Mozilla_preferences#Preferences_Saving

### Proposed solution

Write the changes in `user.js` instead.

Will likely make the script a bit shorter and easier too :)

**Comment by undergroundwires** [comment] 2023-08-11 01:54
Hi @silverhook , thank you for your feedback with nice explanation and sources. Let me know in future if you see any other improvement area, I'm looking forward for this kind of feedback.

You're right. It sounds safer to do changes on `user.js` to not take any chances to corrupt `prefs.js`.

Thinking about the implementation, I guess because `user.js` optional we should do some additional file management in scripts:

- Create `user.js` file in profile folder if not exists.
- On revert, if revert operation resulted in empty `user.js` file, delete the file.

**Comment by undergroundwires** [comment] 2023-09-10 11:52
Fixed by [0.12.3](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.3)

**Closed by undergroundwires** 2023-09-10 11:52 UTC
Labels: enhancement

**Comment by undergroundwires** [comment] 2023-10-16 18:19
Hi @ltguillaume,

Privacy.sexy does no longer touches prefs.js since 0.12.3. See the [code here](https://github.com/undergroundwires/privacy.sexy/blob/67c3677621b201525a813e8a26f07d607176e89b/src/application/collections/linux.yaml#L3690-L3787).

So your flow is right but the step 6. The line does not get removed by privacy.sexy, it just removes the line from `user.js`.

Or did you mean that removing lines `user.js` does not cause Firefox to update `prefs.js`? Should privacy.sexy remove the line from prefs.js as well as `user.js`?

**Comment by undergroundwires** [comment] 2023-11-06 23:51
I can reproduce this. 

It works if privacy.sexy sets the **opposite** value of the desired configuration. But it does not work if privacy.sexy **deletes** the configuration from users.json. And in most cases it should delete the configuration, not to toggle values because the goal is to match the default state and opposite values are not necessarily the default values, default values change over time, and sometimes values are more than booleans.

I will push out Firefox configuration to all operating systems (Windows+macOS) too, so its good to get this stabilized. The only solution looks to be to modify prefs.json only if privacy.sexy is deleting a value on revert. It would be good to verify this with one of the Firefox devs.

I created #282 for this issue only, I appreciate your opinion @atomGit and @silverhook on that issue if you're around.

**Comment by undergroundwires** [comment] 2023-11-06 23:52
I can reproduce this. 

It works if privacy.sexy sets the **opposite** value of the desired configuration. But it does not work if privacy.sexy **deletes** the configuration from users.json. And in most cases it should delete the configuration, not to toggle values because the goal is to match the default state and opposite values are not necessarily the default values, default values change over time, and sometimes values are more than booleans.

I will push out Firefox configuration to all operating systems (Windows+macOS) too, so its good to get this stabilized. The only solution looks to be to modify prefs.json only if privacy.sexy is deleting a value on revert.

I created #282 for this issue only, I appreciate your opinion @atomGit and @silverhook on that issue if you're around.
