### ISSUE TITLE
[BUG] Error 0x80004002 on Microsoft Store when attempting to download an app

### ISSUE THREAD

**Issue by RusticKey** [undergroundwires/privacy.sexy#173] opened 2022-10-14 14:32 UTC
Hello, I just applied [this script](https://github.com/undergroundwires/privacy.sexy/files/9787242/privacy-script.txt) to a fresh installation of Windows 11, and for some reason I couldn't download apps from the Microsoft Store. I reverted the Cloud Experience tweak to allow Microsoft sign-in. Below is the image associated with the problem.

![image](https://user-images.githubusercontent.com/29708207/195871945-19cc86da-c972-40d3-8086-7784f7532e0d.png)
![image](https://user-images.githubusercontent.com/29708207/195872053-bfb2bab4-218d-405c-8b31-7018a52f89c6.png)

I have tried reinstalling Microsoft Store, resetting store cache, etc, and restarting the PC, but nothing seemed to have worked. Thank you.

**Comment by undergroundwires** [comment] 2022-10-15 11:26
Thank you for the nice bug report with all necessary information. It enabled me to troubleshoot this further.

I was be able to reproduce this on Windows 11 22H2, Microsoft Store works fine after running the scripts until restart, the error appears after restart. I tested every script you provided and found out that `Delivery Optimization (P2P Windows Updates)` script causes this. This script works fine on Windows 10 (21H1) causes this issue only on Windows 11.

When I research this I found out that Microsoft seems to change the behavior of Delivery Optimization, before it was used optionally to fetch updates from other Windows users instead of Microsoft servers, now it is even used for Microsoft Store apps. It means that other Windows users connect to your PC to fetch apps/updates from you and you connect to others to download from them. It is not even optional anymore. Read more: [Microsoft blog about it](https://web.archive.org/web/20221004174640/https://support.microsoft.com/en-us/windows/windows-update-delivery-optimization-and-privacy-bf86a244-8f26-a3c7-a137-a43bfbe688e8#WindowsVersion=Windows_11).

Reverting `Delivery Optimization (P2P Windows Updates)` would solve your issue.

I'll issue an update where:
- I'll remove this from Standard pool to Strict recommendation or not recommend it at all.
- Document our finding with this breaking behavior.

Thank you for your contribution and helping to make our software better 👍️.

**Comment by undergroundwires** [comment] 2022-10-15 11:29
Thank you for the nice bug report with all necessary information. It enabled me to troubleshoot this further.

I was be able to reproduce this on Windows 11 22H2, Microsoft Store works fine after running the scripts until restart, the error appears after restart. I tested every script you provided and found out that `Delivery Optimization (P2P Windows Updates)` script causes this. This script works fine on Windows 10 (21H1) causes this issue only on Windows 11.

When I research this I found out that Microsoft seems to change the behavior of Delivery Optimization, before it was used optionally to fetch updates from other Windows users instead of Microsoft servers, now it is even used for Microsoft Store apps. It means that other Windows users connect to your PC to fetch apps/updates from you and you connect to others to download from them. It is not even optional anymore. Read more: [Microsoft blog about it](https://web.archive.org/web/20221004174640/https://support.microsoft.com/en-us/windows/windows-update-delivery-optimization-and-privacy-bf86a244-8f26-a3c7-a137-a43bfbe688e8#WindowsVersion=Windows_11).

Reverting `Delivery Optimization (P2P Windows Updates)` would solve your issue.

I'll issue an update where:
- I'll remove this from Standard pool to Strict recommendation (because it still shares considerable amount of data).
- Document our finding with this breaking behavior.

Thank you for your contribution and helping to make our software better 👍️.

**Comment by rounk-ctrl** [comment] 2022-10-26 19:13
I had this same issue and found out that it was due to the Windows Firewall service being disabled. So after I enabled the service, uwp apps work

**Comment by daureg** [comment] 2022-12-16 22:58
I got  a similar problem on Windows 10 22H2 (19045.2364) but strangely enough only for installing xbox games, not other apps from the store.
I first got a hint it was related to the Delivery Optimization service from this [xbox forum post](https://answers.microsoft.com/en-us/xbox/forum/all/xbox-game-pass-install-error-0x800700e9-on-pc/252cb198-8484-4d31-a017-0548450057a9) and it was indeed solve by re-enabling it
Here are some screenshot (in French) showing that I could install Netflix from the store but not update Forza 4 there, nor in the xbox app (error 0x80080206), nor install a new game (Potion craft, error 0x800700e9)
![2022-12-16 23_45_15-Microsoft Store](https://user-images.githubusercontent.com/19685/208202246-8afe4357-99ff-4d36-b1c7-42f9af9f157d.png)
![2022-12-16 23_45_50-Xbox](https://user-images.githubusercontent.com/19685/208202243-20700147-1de9-4098-8b77-4d201001fb20.png)
![2022-12-16 23_44_49-Xbox](https://user-images.githubusercontent.com/19685/208202248-ec9f2b12-3ec3-43bb-919d-4d6ed759e1b7.png)

**Comment by Abyssgrowth** [comment] 2023-02-26 17:31
Simply don't use MS Store, it's garbage spyware period.
To play minecraft use technic launcher which allows you to login with mojang account aswell. F microsoft.

**Comment by Ristavor** [comment] 2023-09-08 15:07
Addition: using delivery optimization script also breaks windows update feature (cannot download any updates). To repair: revert this script
System: windows 11

**Comment by undergroundwires** [comment] 2023-09-08 20:46
Do we have any source related to this causing Windows Updates to not work? Is there anyone else that can reproduce/verify this issue? As I interpret Microsoft documentation this feature is optional ([**can be** used to reduce bandwidth consumption](https://learn.microsoft.com/en-us/windows/deployment/update/wufb-reports-do)), however the way we disable this may still cause this.

If it breaks Windows Updates, it's too much, we should move this under `Disable Windows updates`, do not recommend it all on any level, and instead do a more standard/proper/non-intrusive way ([source 1](https://learn.microsoft.com/en-us/windows/deployment/do/waas-delivery-optimization-reference#download-mode), [source 2](https://www.stigviewer.com/stig/windows_10/2019-01-04/finding/V-65681)). This does not seem to guarantee disabling it completely, but disabling `DoSvc` is doing too much.

**Comment by undergroundwires** [comment] 2023-09-26 14:12
The fix is released in [0.12.4](https://github.com/undergroundwires/privacy.sexy/releases/0.12.4) 🚀.

**Closed by undergroundwires** 2023-09-26 14:12 UTC
Labels: bug

**Comment by Zahid-C** [comment] 2025-01-07 17:05
> Do we have any source related to this causing Windows Updates to not work? Is there anyone else that can reproduce/verify this issue? As I interpret Microsoft documentation this feature is optional ([**can be** used to reduce bandwidth consumption](https://learn.microsoft.com/en-us/windows/deployment/update/wufb-reports-do)), however the way we disable this may still cause this.
> 
> If it breaks Windows Updates, it's too much, we should move this under `Disable Windows updates`, do not recommend it all on any level, and instead do a more standard/proper/non-intrusive way ([source 1](https://learn.microsoft.com/en-us/windows/deployment/do/waas-delivery-optimization-reference#download-mode), [source 2](https://www.stigviewer.com/stig/windows_10/2019-01-04/finding/V-65681)). This does not seem to guarantee disabling it completely, but disabling `DoSvc` has too many side-effects.

I got the same error code in computer today. 

![error_png](https://github.com/user-attachments/assets/a90abdd4-f08a-4e67-9949-ce7fd6fee990). 

I reverted " _Disable obtaining updates from other PCs on the Internet (delivery optimization)_ " , [solution.txt](https://github.com/user-attachments/files/18336085/solution.txt) , and rebooted the system. Windows Update is working normally right now.



Operating System: Windows 11 IoT Enterprise LTSC 64-bit (10.0, Build 26100)

**Comment by undergroundwires** [comment] 2025-03-13 14:03
🚀 In [0.13.8](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.13.8), disabling `DoSvc` is no longer recommended, script is renamed and documentation in improved based your feedback @woshiahmedc, thank you.
