### ISSUE TITLE
[BUG]: Network & Internet Problem after using the script

### ISSUE THREAD

**Issue by RealTengo** [undergroundwires/privacy.sexy#166] opened 2022-08-30 14:37 UTC

**Comment by NaiJii** [comment] 2022-09-11 09:57
same issue here.

**Comment by nooisy** [comment] 2022-09-17 14:56
I have this issue as well on the same Win10 build. 

Opening "Network & Internet settings" via the taskbar or Windows Settings produces the following popup:
"Settings: SystemSettings.exe - System Error : The system detected an overrun of a stack-based buffer in this application. This overrun could potentially allow a malicious user to gain control of this application."
Closing this popup results in the (blank) Settings window to immediately crash.

I used the Strict preset. SFC nor DISM can fix this problem. Curiously enough this problem does not persist when booted into safe mode. Resetting network settings while in safe mode also didn't help.

**Comment by nooisy** [comment] 2022-09-17 15:13
This is a known consequence of disabling the Windows Push Notification Service. privacy.sexy also offers a script to reverse this: you can search for the mentioned service on the configuration website and toggle the "revert" button.

**Comment by undergroundwires** [comment] 2022-09-25 17:24
Hi, thank you @nooisy . This script is heavily documented but after #110 and this breaking behavior is not a bug. It's still in the strict pool because of the comment you'll see on other issue. I think the biggest problem is that UI is not clear enough for the breaking scripts, they should be red, double-confirmed etc. Please let me know if you think this script should be removed from the "Strict" pool, otherwise I'm closing this issue as it is not a bug.

**Closed by undergroundwires** 2022-09-25 17:24 UTC
Labels: bug
