### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by DeadmanIsJacob** [undergroundwires/privacy.sexy#405] opened 2024-08-09 01:21 UTC
### Problem statement

When Running the Script to help clean and remove non-essentials, I would like to know whether the script has been already ran. 

### Proposed solution

An indicator that tells whether this script has already ran. So as to not run the script again and cause an error.     

### Additional information

For Example, under, "Disable OS data collection," and "Disable App access to personal information"  There is an indicator that tells you already run this script, or "this feature is already activated on your computer".

**Comment by undergroundwires** [comment] 2024-08-09 08:07
Hi do you mean that on the UI or during script execution in script logs/output?

**Comment by CodingMadness** [comment] 2024-09-22 10:36
> Hi do you mean that on the UI or during script execution in script logs/output?

would be best on the UI, so the respective checkbox gets sort of automatically a red when trying to check it while it actually is already happening/running on your system.

**Comment by undergroundwires** [comment] 2024-10-02 19:42
Duplicate of #307. @CodingMadness I'm looking for any good UI design for this. Making the checkbox red implies **danger** which is not the case here. Maybe something else? Closing this in favor of #307.

**Closed as completed by undergroundwires** 2024-10-02 19:42 UTC
Labels: enhancement
