### ISSUE TITLE
What script disables the night light settings?

### ISSUE THREAD

**Issue by AdamJel** [undergroundwires/privacy.sexy#54] opened 2021-02-03 17:12 UTC
Hello,
I used this script generator to harden privacy on my Win machine. I also tried to remove as much bloatware as possible. I am overall happy except for one thing. The Windows settings of night light is inaccessible. 

Do you know, which script could have disabled this feature and what would be his reverse form?

Thank you

**Comment by undergroundwires** [comment] 2021-02-04 11:28
Hi, glad to hear that you're overall happy and thanks for the bug report. I can reproduce this. It's unintended. I don't see what's causing it on a quick look 🤔

**Comment by undergroundwires** [comment] 2021-02-04 11:48
Hi, glad to hear that you're overall happy and thanks for the bug report. I can reproduce this. It's unintended. I don't see what's causing it 🤔

**Comment by undergroundwires** [comment] 2021-02-04 20:51
Hi @AdamJel , glad to hear that you're happy an d thanks for the bug report. Would you be able to specify your OS version? Did you run standard/script or something customized? Could you upload the script if it was something customized?

**Comment by undergroundwires** [comment] 2021-02-04 20:51
Hi @AdamJel , glad to hear that you're happy and thanks for the bug report. Would you be able to specify your OS version? Did you run standard/script or something customized? Could you upload the script if it was something customized?

**Comment by AdamJel** [comment] 2021-02-05 08:14
@undergroundwires luckily, I am able to catch on your message editing going on :) 
- My OS = Windows 10 - 20H2 - 19042.789
- I only run scripts from the app. I selected strict option and went through the list and selected and unselected some more. I am not 100 % sure, but most likely, I run these scripts:
[cortane.txt](https://github.com/undergroundwires/privacy.sexy/files/5931032/cortane.txt)


[hyper.txt](https://github.com/undergroundwires/privacy.sexy/files/5931033/hyper.txt)
[office.remove.txt](https://github.com/undergroundwires/privacy.sexy/files/5931034/office.remove.txt)
[settings.txt](https://github.com/undergroundwires/privacy.sexy/files/5931035/settings.txt)
[update.txt](https://github.com/undergroundwires/privacy.sexy/files/5931036/update.txt)

**Comment by undergroundwires** [comment] 2021-02-05 18:23
Hi, sorry for the inconsistent replies, I was testing meanwhile and getting different result 😅 Thanks for the all information.

I tested it on 20H1 but could not reproduce, however I could reproduce it using 20H2 and "Strict" template after rebooting.

Behavior is unintended and I'm not sure what script is causing it. 🤔

**Comment by undergroundwires** [comment] 2021-02-26 17:21
I suspect this is caused by disabling a service that interacts with the night light settings in an undocumented way. https://github.com/undergroundwires/privacy.sexy/issues/55#issuecomment-785181443 by @mikhoul might solve it. Please share if anyone can find out what's the cause here, so we can unrecommend or document the script.

**Comment by mikhoul** [comment] 2021-02-27 16:35
There are 3 Windows services necessary for night lighting to work properly:

- Connected Devices Platform User Service (CDPUserSvc)

- Connected Devices Platform Service (CDPSvc)

- Network Connection Broker (NcbService)

If the "Connected Devices Platform Service" and "Network Connection Broker" services have the "disabled" start type, the "night lighting" functionality in the "Settings" application does not work, if we click on the button for the activate, nothing happens. For the night lighting setting to work, these services can be configured with the "manual" or "automatic" start type with the service management console (services.msc).

The "Connected Devices Platform User Service" service must be configured with the "automatic" start type for night lighting to work. This service (called "template service") create a secondary service (called "Per-user service") with the same name followed by a random hexadecimal number (ex: Connected Devices Platform User Service_253cb) when a user log in (source: https://docs.microsoft.com/en-us/windows/application-management/per-user-services-in-windows).

This service cannot be configured with services.msc, so you must modify its configuration with the Windows registry by executing these commands in Administrator:

reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\CDPUserSvc" /v Start /t REG_DWORD /d 2 /f

reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\CDPUserSvc" /v UserServiceFlags /t REG_DWORD /d 3 /f

Setting the value "Start" to 2 configures the type of start to "Automatic".

Setting the value "UserServiceFlags" to 3 allows the creation of the service per user.

When a user log in, the created per-user service inherits the configuration parameters from the service template. So, if the value "Start" of the template service is 2, the service per user created will have the same value "Start" to 2.

After applying these settings, restart the computer and test the night lighting again.


**Source:** _https://answers.microsoft.com/en-us/windows/forum/all/cant-use-windows-night-light-feature/a7372273-ef97-490e-a65e-5a73d714348c_

**Comment by usamac** [comment] 2021-04-02 15:07
Hello @mikhoul 

I am having this issue after running Standard with some modifications. I have removed EDGE, MS Edge, OneNote & One Drive. There may be one other thing I allowed it wanted to remove that I cannot recall.  

I am on 20H2 with Build 19042.906 and Windows Feature Experience Pack 120.2212.551.0. 

After running the script, I restarted my system. Then I happened to notice that Night Light was broken. (I use it famously on all of my systems.) 

Via your instructions above, searched the services.msc and found both of the aforementioned  "Connected Devices Platform Service (CDPSvc)" which was set to Automatic (Delayed Start) and "Network Connection Broker" was set to Manual (Trigger Start). Both were currently Running.

"Connected Devices Platform User Service" was set to Automatic and it was Running. 
So, I opened properties and toggled it to Automatic, applied, closed and restarted my system. Once loaded in I checked and Night Light was still greyed out. 

I went back into check what they were showing in service.msc and found that "Connected Devices Platform User Service" was no longer even present in any way. 

At this point I opened cmd in admin and ran the two lines one at a time just as you posted above. Both ran successfully. 
I then restarted and once loaded in found that Night Light was still greyed out. I then searched for Night Light setting to check if I had any options there. 

services.msc still does not show "Connected Devices Platform User Service" at all. 

Could you provide any other suggestions? It is strange because I have run a very similar script on work devices and while I left OneNote, Drive and Edge enabled, there are no other differences in these two scripts.  Work machines are not losing Night Light.

[privacy-script personal.zip](https://github.com/undergroundwires/privacy.sexy/files/6250094/privacy-script.personal.zip)

**Comment by mikhoul** [comment] 2021-04-02 17:40
> services.msc still does not show "Connected Devices Platform User Service" at all.

Make sure that the CDPUserSvc.dll file exists in the %WinDir%\System32 folder. If this file is missing you can try to restore it from your Windows 10 installation media.

**Comment by usamac** [comment] 2021-04-02 23:14
I believe it is installed, right?

![Screenshot 2021-04-02 191234](https://user-images.githubusercontent.com/55719365/113460676-87341d00-93e7-11eb-814f-e9d771a1934e.png)

**Comment by mikhoul** [comment] 2021-04-03 03:28
Verify that the DDL is registred: https://helpdeskgeek.com/how-to/register-dll-file-in-windows/

Once registered set the service to automatic and reboot so see if the service is started.

**Comment by usamac** [comment] 2021-04-04 00:43
Thank you. I did this and then the freaking thing disappeared again after reboot. I ended up running sfc/ scannow and it restored my Night Light. Searching through the logs.. unsure so far, but I am wondering if this enabled my telemetry back as well though?

**Comment by undergroundwires** [comment] 2021-11-19 15:48
I found this out after some extensive testing. It's `Microsoft AAD Broker Plugin` script. Uninstalling it breaks night light settings after reboot. Same behavior is also seen on Windows 10 21H1 and Windows 11 - 21H2. Reverting the script and rebooting solves the issue.

**Comment by undergroundwires** [comment] 2021-11-19 15:50
I found this out after some extensive testing. It's `Microsoft AAD Broker Plugin` script. Uninstalling it breaks night light settings after reboot. Reverting the script and rebooting solves the issue.

Also breaks on Windows 10 21H1 and Windows 11 - 21H2.

I don't know why night light setting would require Azure Active Directory connection. High likely that some data collection is involved.

**Comment by usamac** [comment] 2021-11-21 12:57
That is very interesting! I've been experimenting with Win 11 some but have
not used your debloating scripts with it yet.

Thank you for looking into it further and for letting me know of your
findings!

--
*Nick*
***@***.***

**Comment by undergroundwires** [comment] 2022-01-26 01:31
Closing this as the setting is now unrecommended and documented. Feel free to create new issues for further problems/ideas.

**Closed by undergroundwires** 2022-01-26 01:31 UTC
Labels: bug
