### ISSUE TITLE
[BUG]: Standard Privacy Script mess with some online games

### ISSUE THREAD

**Issue by SoyLevelMax** [undergroundwires/privacy.sexy#181] opened 2022-11-17 00:24 UTC
Simply has that, I put the Standard Privacy, and then I realize that a lot of Online games and "app Store" stop working (Xbox Game Pass, Battle.Net, Oculus VR googles, etc) some URL sites and I can't even upgrade Google Chrome... I use the "Rever" feature... but that not working at all.

Are there some Script to backroll every changes that this program made? 

Maybe this privacy scripts are not made for gamers

Thanks.

**Comment by Fnoberz** [comment] 2022-12-01 01:25
yes i agree When I opted for Standad Privacy, it prevented me from playing games on my Xbox and my Google Chrome said **Managed by your organization** so I had to revert everything. But it didn't work either.

- Unable to update game or xbox
- Unable to download games on Xbox Game pass.

And hope you fix the scripts it soon so that it can work well for playing games.

**Comment by SoyLevelMax** [comment] 2022-12-01 04:40
I can't connect with:

EA App
Origin
Battle.Net
Battlestate

I don't wanna Reinstall Windows... I Hope can revert this terrible mess up with the standard security, I have purchase a lot of games  and I can't play it.

**Comment by Fnoberz** [comment] 2022-12-01 11:43
You can revert everything by selecting All Scripts and selecting the original values.

**Comment by Fnoberz** [comment] 2022-12-01 11:44
If unable to use, Screenshot message that appears when the game cannot be opened. Maybe I can help you.

**Comment by SoyLevelMax** [comment] 2022-12-02 23:24
> 

Not everything, a lot of tweaks no have the Revert option.

**Comment by Fnoberz** [comment] 2022-12-07 18:54
@SoyLevelMax Everything has a rollback option. please make sure

**Comment by MiRw3b** [comment] 2022-12-11 18:28
agreed that this happens to me too, except i was almost at "all" preset (customized)
i tried reverting the changes made to the windows defender firewall, doesnt seems to work, theres an app that throws me an error about firewall, so my guess would be that its related to it

**Comment by SoyLevelMax** [comment] 2022-12-11 19:12
> @SoyLevelMax Everything has a rollback option. please make sure

I'm 150% sure...

**Comment by Tyestor** [comment] 2023-01-12 06:10
this thing hasn't been updated for almost a year, people need to stop using it.

**Comment by undergroundwires** [comment] 2023-12-05 21:55
Hi, sorry for coming back late, I had some life things going on for some time and once I was back I started cleaning up issues from to top, so it took a while to see this.

Thank you @LoneDev6 for the concrete suggestion. So we identified that  `XboxIdentityProvider` breaks log-in to some games. We should then move it to "Strict" (now it's part of "Standard"), document breaking behavior in script title and its docs, move it to "Strict". I will add this to next patch release.

The issue got a bit old and I'm not sure if you found any other root cause for this. Btw, @MiRw3b you would never want to run "All", it is not meant for daily OS users. I will update documentation to make it more clear in next feature version.

I had no reports before that any of the script has been causing visiting website or blocking Google Chrome upgrades. I'm not sure this is caused by any of the existing scripts, but if someone else does have these issues please create a new GitHub issue with the script you generated so we can try to reproduce it further.

**Comment by undergroundwires** [comment] 2023-12-16 04:26
Xbox Identity Provider (`XboxIdentityProvider`) is documented and removed from Standard pool. Released in [0.12.9](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.9) 🚀 Let me know if you still have issues with gaming on Standard pool, and we'll fix them right away.

**Closed by undergroundwires** 2023-12-16 04:26 UTC
Labels: bug

**Comment by schm0** [comment] 2024-07-02 19:05
The "Improve network security" part breaks battle.net

**Comment by undergroundwires** [comment] 2024-07-06 12:01
> The "Improve network security" part breaks battle.net //edit sha-1 is needed for battle.net...

Thanks for the info @schm0, I'm sure it would helpful for others that had issues.

I do not know to incorporate this information in privacy.sexy though. The script is well-documented, it's on Strict level and it's Blizzard's responsibility to follow security best-practices.

**Comment by zdat** [comment] 2024-07-19 17:46
> The "Improve network security" part breaks battle.net //edit sha-1 is needed for battle.net...

He's an absolute soldier.
