### ISSUE TITLE
[BUG]: Edge and Onedrive remains in programs list

### ISSUE THREAD

**Issue by SalaryTheft** [undergroundwires/privacy.sexy#194] opened 2023-01-13 12:11 UTC
### Description
Edge and Onedrive is still in programs list after removing it with the script.

### OS
Windows 11 22H2 22621.1105

### Script
[privacy-script.txt](https://github.com/undergroundwires/privacy.sexy/files/10411339/privacy-script.txt)

### Screenshots
![image](https://user-images.githubusercontent.com/72844671/212317246-af9c0607-903a-4d20-9aaa-154ed1ca38a9.png)

**Comment by undergroundwires** [comment] 2023-10-02 13:36
Hi @SalaryTheft, thank you for the bug report and sorry for my late response.

I can reproduce this:

1. Started clean Windows 11 22H2 machine.
2. Execute the script you provided.
3. Reboot the machine
4. Open Control Panel > Add or Remove Programs (or Apps > Install Apps)
5. Microsoft OneDrive is not there, Microsoft Edge is not there.

But, when I run the latest version of privacy. sexy ([0.12.4](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.4)), OneDrive disappear from installed apps list. OneDrive seems to be fixed in 58ed7b456b3cf11774c83c8c1c04db37ef3058c2, released in ([0.12.0 (3 Aug 2023)](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.0)), its uninstaller properly removes OneDrive from the list.

However,  neither uninstalling Edge chromium or legacy remove Microsoft Edge from the application list. So this needs to be fixed.

**Comment by undergroundwires** [comment] 2023-10-02 13:37
Hi @SalaryTheft, thank you for the bug report and sorry for my late response.

I can reproduce this:

1. Started clean Windows 11 22H2 machine.
2. Execute the script you provided.
3. Reboot the machine
4. Open Control Panel > Add or Remove Programs (or Apps > Install Apps)
5. Microsoft OneDrive is not there, Microsoft Edge is not there.

But, when I run the latest version of privacy. sexy ([0.12.4](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.4)), OneDrive disappear from installed apps list. OneDrive seems to be fixed in 58ed7b456b3cf11774c83c8c1c04db37ef3058c2, released in ([0.12.0 (3 Aug 2023)](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.0)), its uninstaller properly removes OneDrive from the list.

However,  neither uninstalling Edge chromium or legacy remove Microsoft Edge from the application list. Its uninstaller does not do the job. So this needs to be fixed.

**Comment by undergroundwires** [comment] 2023-10-02 13:41
Hi @SalaryTheft, thank you for the bug report and sorry for my late response.

I can reproduce this:

1. Started clean Windows 11 22H2 machine.
2. Execute the script you provided.
3. Reboot the machine
4. Open Control Panel > Add or Remove Programs (or Apps > Install Apps)
5. Microsoft OneDrive is there, Microsoft Edge is there.

But, when I run the latest version of privacy. sexy ([0.12.4](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.4)), OneDrive disappear from installed apps list. OneDrive seems to be fixed in 58ed7b456b3cf11774c83c8c1c04db37ef3058c2, released in ([0.12.0 (3 Aug 2023)](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.0)), its uninstaller properly removes OneDrive from the list.

However,  neither uninstalling Edge chromium or legacy remove Microsoft Edge from the application list. Its uninstaller does not do the job. So this needs to be fixed.

**Comment by undergroundwires** [comment] 2023-11-04 12:47
Fixed and released in [0.12.6](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.12.6) 🚀 solution was to remove appx package. Please create a new issue in future if you detect something.

**Closed by undergroundwires** 2023-11-04 12:47 UTC
Labels: bug
