### ISSUE TITLE
[BUG]: Can't access sign-in options nor create a restore point

### ISSUE THREAD

**Issue by lalo311** [undergroundwires/privacy.sexy#81] opened 2021-06-13 22:49 UTC
### Describe the bug

Hey, I wanted to try your scripts but now my windows settings freeze/hang when I try to access the sign-in options section and I also can't access the restore point feature, is it expected ?

### OS

Win 21H1 build 19043.1052

### Screenshots

![image](https://user-images.githubusercontent.com/61351254/121823915-9289ab80-cca8-11eb-98fe-5f3135df3687.png)

### Scripts

[privacy-script.txt](https://github.com/undergroundwires/privacy.sexy/files/6644780/privacy-script.txt)

**Comment by undergroundwires** [comment] 2021-10-17 15:53
Hi @Ayeki, thank you for the response, I'm sorry for late response and the inconvenience.. I can reproduce this. It's probably caused by disabling VSS.

Please try to revert: `Volume Shadow Copy Service` script that you applied.

In latest version ([v0.10.3](https://github.com/undergroundwires/privacy.sexy/releases/tag/0.10.3)) VSS script is no longer documented, and breaking behavior is documented.

Please let me know if it solved your problem or not.

**Comment by undergroundwires** [comment] 2024-02-18 21:47
This has been documented for a while. Closing this issue.

**Comment by undergroundwires** [comment] 2024-02-18 21:47
No feedback from the OP, closing the issue.

**Closed by undergroundwires** 2024-02-18 21:47 UTC
Labels: bug
