### ISSUE TITLE
[BUG]: Running the script broke Windows Store login; unable to install any Store apps due to error 0x800704cf

### ISSUE THREAD

**Issue by smukherjee2016** [undergroundwires/privacy.sexy#100] opened 2021-10-11 20:13 UTC
### Description

I ran the following attached script (renamed to .txt so that Github accepts the upload) after generating it from the program (Awesome program btw, thanks! My PC runs much quieter for some reason now!).

However, after running it and rebooting, my ToDo account showed me as offline, and thinking something was wrong with the app, I uninstalled it. But then I was unable to reinstall it or any other apps due to this error.

### OS

Windows 10 Education 20H2

### Reproduction steps

Run the script attached on a PC with a local Microsoft account.
Reboot and open Microsoft Store, and try to install an app.

### Screenshots

When I click "Get" on a Microsoft store app, it first asks me to sign in, and when I select the account, it shows the following message:

![2021-10-12 05_06_59-Microsoft Store](https://user-images.githubusercontent.com/6712929/136850068-5f11f271-caab-4dbe-8de2-2178f7e4be2f.png)

### Additional information

Weirdly enough, after reverting some changes (specifically searching for ones with "break" and reverting them), it seems updating installed apps works, but apps themselves don't seem to connect successfully.

Also, unfortunately I realized the problem too late so I don't have an automatic restore point before I ran the script, and I didn't generate a manual one when I ran it...

Any help would be appreciated!

**Comment by ScribbleGhost** [comment] 2021-11-01 19:06
Just to let you guys know I have had this problem with Store not connecting without running this script. The problem happened after some connection issues on my router (probably DNS issues). After a reboot of the router and a reboot of the computer the problem was not there anymore.

**Comment by undergroundwires** [comment] 2021-11-16 15:10
Thank you guys sharing information. @smukherjee2016  that's very constructive and great report 👍 I tested disabling `UnistoreSvc` and `Disable active probing` but could not reproduce the issues. Let's keep this issue here to see if others would have similar problems.

**Comment by Evineit** [comment] 2021-12-28 20:24
I had the same problem, the script used was the standard in the main page.
To solve it I had to revert "disable Microsoft Windows Live ID Service".
Maybe it shouldn't be selected on the standard configuration recommend to everyone.

**Comment by Cebrain** [comment] 2022-01-02 12:02
> I had the same problem, the script used was the standard in the main page. To solve it I had to revert "disable Microsoft Windows Live ID Service". Maybe it shouldn't be selected on the standard configuration recommend to everyone.

Thanks, this fixed the problem for me

**Comment by undergroundwires** [comment] 2022-01-02 17:19
Thanks @Evineit , nice to find out the cause of it.

I tested on Windows 10 21H2 and get:

```txt
PUR-AuthenticationFailure
v3ZtcNH7IECS00iL.36.1
```

And on Windows 10 21H1: `0x800706d9`.

On both versions reverting Windows Live ID Service solved the issue.

I'll document the breaking behavior and unrecommend it with a patch.

**Comment by undergroundwires** [comment] 2022-03-06 17:19
Closing this because the behavior is now documented and script causing it is unrecommended.

**Closed by undergroundwires** 2022-03-06 17:19 UTC
Labels: bug

**Comment by feinersaft** [comment] 2023-10-01 17:51
Hi, I currently receive this error code too after running the "Standard" script pack. I only switched off some scripts which I knew I would want to keep. So I think there is still a script that breaks Windows Store. Here is a list of the scripts I ran:
[custom-privacy-script.txt](https://github.com/undergroundwires/privacy.sexy/files/12777830/custom-privacy-script.txt)

**Comment by undergroundwires** [comment] 2023-10-01 20:29
Hi @feinersaft , it has been renamed to `Microsoft Account Sign-in Assistant` but I see did you did not run it. It's great that you shared the script you have. Could you create a new github issue for what you experienced? This way it would get more attention and we can have separate focus on solving this/track progress. It would be nice if you could share also how you know that the store is gone, what error you're getting, screenshot etc. Issue template when creating a new issue would guide you.

**Comment by ScribbleGhost** [comment] 2023-11-03 18:21
I have come to realize that this only happens when my VPN Private Internet Access is connected (though in split mode). Not sure if this applies to everyone here.
