### ISSUE TITLE
[BUG]: Dropbox Client no longer works with the script to disable Automatic Update Services applied

### ISSUE THREAD

**Issue by Dario011** [undergroundwires/privacy.sexy#189] opened 2022-12-27 18:27 UTC
### Description
When using the scripts to disable Dropbox Automatic Updates Service, the client becomes unusable, it shows me the following message "Your device has no internet connection. Please try again", and it stays in "Connecting..." and never starts.

### OS

Windows 10 21H2 (OS Build 19044.2364)

### Reproduction steps

1. Execute the script (which has, among other things, the deactivation of Dropbox updates activated).
2. Open Dropbox Client (version 163.4.5456)
3. See "no internet" errors and stays on "Connecting..." forever.

### Scripts

[privacy-script.txt](https://github.com/undergroundwires/privacy.sexy/files/10310036/privacy-script.txt)

### Screenshots

![Captura de pantalla 2022-12-27 151450](https://user-images.githubusercontent.com/95557625/209706505-4ce9c18c-87c0-41eb-bc70-2c9760da54d0.png)
![Captura de pantalla 2022-12-27 151525](https://user-images.githubusercontent.com/95557625/209706519-4cd68418-bedf-4f8e-94ef-538bf21893d4.png)

### Additional information

Even if I have applied the script to revert it, it does nothing, even if you do a reboot, nothing changes.

**Comment by deltabeard** [comment] 2023-06-08 22:29
I have hit this bug with Dropbox v175.4.5569.

**Comment by undergroundwires** [comment] 2023-09-22 23:55
Thank you for the quality issue @Dario011 with helpful details including script file. Can this be caused by `Disable active probing (pings to MSFT NCSI server)`? As you verified, this does not seem to be caused by the dropbox scripts.

Let me know if reverting this solves the issue for anyone, if we identify that it's the case, we should document this script can break third party apps online status, and I guess dropbox devs should have done better for the connectivity check.

<details>
  <summary>Revert script</summary>
  
```batchfile
@echo off
:: https://privacy.sexy — v0.12.3 — Fri, 22 Sep 2023 23:49:51 GMT
:: Ensure admin privileges
fltmc >nul 2>&1 || (
    echo Administrator privileges are required.
    PowerShell Start -Verb RunAs '%0' 2> nul || (
        echo Right-click on the script and select "Run as administrator".
        pause & exit 1
    )
    exit 0
)


:: Disable active probing (pings to MSFT NCSI server) (revert)
echo --- Disable active probing (pings to MSFT NCSI server) (revert)
reg add "HKLM\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet" /v "EnableActiveProbing" /t REG_DWORD /d "1" /f
:: ----------------------------------------------------------


pause
exit /b 0
```
</details>

**Comment by undergroundwires** [comment] 2023-09-22 23:56
Thank you for the quality issue @Dario011 with helpful details including script file. Can this be caused by `Disable active probing (pings to MSFT NCSI server)`? As you verified, this does not seem to be caused by the dropbox scripts.

Let me know if reverting this solves the issue for anyone, if we identify that it's the case, we should document that this script can break third party apps connectivity checks, and dropbox devs should have done better..

<details>
  <summary>Revert script</summary>
  
```batchfile
@echo off
:: https://privacy.sexy — v0.12.3 — Fri, 22 Sep 2023 23:49:51 GMT
:: Ensure admin privileges
fltmc >nul 2>&1 || (
    echo Administrator privileges are required.
    PowerShell Start -Verb RunAs '%0' 2> nul || (
        echo Right-click on the script and select "Run as administrator".
        pause & exit 1
    )
    exit 0
)


:: Disable active probing (pings to MSFT NCSI server) (revert)
echo --- Disable active probing (pings to MSFT NCSI server) (revert)
reg add "HKLM\SYSTEM\CurrentControlSet\Services\NlaSvc\Parameters\Internet" /v "EnableActiveProbing" /t REG_DWORD /d "1" /f
:: ----------------------------------------------------------


pause
exit /b 0
```
</details>

**Comment by Dario011** [comment] 2023-09-23 01:03
> Thank you for the quality issue @Dario011 with helpful details including script file. Can this be caused by `Disable active probing (pings to MSFT NCSI server)`? As you verified, this does not seem to be caused by the dropbox scripts.
> 
> Let me know if reverting this solves the issue for anyone, if we identify that it's the case, we should document that this script can break third party apps connectivity checks, and dropbox devs should have done better..

Good evening, I imagined that I would never have any answer to this problem....
Unfortunately, there is not much I can do, since I switched from Windows to Linux several months ago.
From what I remember, I used that script to disable updates, and Dropbox literally never worked again (I even used that revert script, and nope, searching this specific solution in internet it was completely useless), in fact I had to format it to make it work.

**Comment by undergroundwires** [comment] 2023-09-23 08:37
Thank you for the update. I'm sorry for late response, life things lately and missed this issue. This kind of side-effects are not intended and can be considered bug. We should handle this if anyone else that encounters this problem gives us more context.

P.S.: I also switched to Linux, added Linux support in recent versions. Linux will be first-class citizen in privacy.sexy.

**Comment by undergroundwires** [comment] 2023-12-16 04:47
Closing this as we cannot reproduce this anymore. If anyone else experiences this in future, feel free to create a new issue or re-open this with help request or just by sharing more insights.

**Closed by undergroundwires** 2023-12-16 04:47 UTC
Labels: bug, blocked/need-repro
